Build app
pastorp3/Weather-App pull request #1
Opened 2020-10-27 20:08 UTC by pastorp3

2020-10-27 22:35 UTC, mikenath223 requested changes
### Hello @pastorp3 👋

**You've done quite well on this.👍**

**STATUS: CHANGES REQUESTED**👷‍♂️

- [x] OPTIONAL -  Consider fetching the geolocation of the user when the app is first accessed and then fetch the weather from that location, it would help to improve user experience.

- [x] Please refer to comments on your code.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-10-27 22:39 UTC, mikenath223 commented on src/getdata.js
> +    alert(error);
- [ ] IMPORTANT - Please avoid using Window.alert in your code. Kindly remove this and all other cases where you added it. Handle errors in a better way. Window.alerts are ugly, impossible to style, stop code execution and display differently on different browsers. Use custom modal instead. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/alert_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/javascript-module-v-10/166782/path/step/97634928/))

2020-10-27 23:52 UTC, pastorp3 commented
Add review changes:
 - Delete window.alert()

2020-10-28 01:10 UTC, bellom approved these changes
## Hi @pastorp3  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-10-28 01:12 UTC, merged